### ISSUE TITLE
Scan Off-hand and head slot as well

### ISSUE THREAD

**Issue by FlawlessMC** [kangarko/Confiscate#158]
Hello, the plugin can mostly be bypassed using off-hand slot and head-slot.
would it be possible to add so the plugin also scans those areas?
and possibility to scan "on-use"
for example. using a water bucket to place water. and you have it blacklisted, it removes the waterbucket.

**Comment by kangarko** [comment]
Thanks, I'll add this in a few days.

**Comment by kangarko** [comment]
I fixed the bug! For now, we do not plan adding scanning on use, because we already tried and the interactevent scan drags the performance down and was a bit unstable, it was a mess. I believe there are better ways in you not having the item water bucket, such as disabling its crafting recipe instead. Or did you mean using it in another way?

**Comment by FlawlessMC** [comment]
Awesome, thank you so much!
Yeah I just simply need to make the item completely banned in a specific world, so that players can't abuse water ascension glitches

________________________________

**Comment by kangarko** [comment]
I do recommend a custom solution for this, that would be out of scope of Confiscate plus just listening to "on use" is not enough imho.
