### ISSUE TITLE
An error, two suggestions, and a question.

### ISSUE THREAD

**Issue by Mxra** [kangarko/Confiscate#34]
**Error**
`Scan.When_Clicking` has yet another error, this time it's with eating food. If a player looks at a block and tries to eat with this setting enabled their animation will be cancelled due to the scanning, meaning they can never finish eating unless they look at air.

**Suggestion 1**
You could add mcMMO enchanted item support. For example, activating a "Super Breaker" will give the item +5 efficiency, I believe. Making it go over maximum vanilla enchant levels even if your item beforehand has Efficiency 1, it will go to 6...

**Suggestion 2**
You could add an `Allow_Strictness` filter for levels 1-2, giving us the ability to choose exactly what lore/name it ignores, for example a string list.

**Question**
Also, a quick question, does having a `Too_High` exception also take into account lower levels? For example, if I set it to ignore `DIG_SPEED: 10`, would it ignore 9-8-7-etc... or would I have to add all of those manually?

**Comment by kangarko** [comment]
Hello,

thank you for using Confiscate and pointing out those things. 

**Error**: I reviewed the code and for the time being it is not in my reach to make it not happen in that way. I recommend you disable When_Clicking scanning and rely only on scanning when opening a container or joining the game - I used those myself and it'll do most of the job. I will test it some more when I have more time but scanning when clicking has always been problematic due to the nature of the API I have of disposal.

**Suggestion 1**: This will be fixed if you disable scanning when clicking as suggested above. Not that I am suggesting not using certain parts of the plugin, but I am saying that that one particular option is problematic and Confiscate's functionality remains using the other types of scan.

**Suggestion 2**: Thanks, I've noted that down as a suggestion.

**Question**: Yes it will ignore all levels up to level 10 :)
