### ISSUE TITLE
Java exception in console

### ISSUE THREAD

**Issue by ICEconchy** [kangarko/Confiscate#36]
Error in console:
https://hastebin.com/koriheweju.sql

**Comment by kangarko** [comment]
Remove data.db and your physical chest room and set the cornerstone again.

**Comment by ICEconchy** [comment]
I am still receiving the error

**Comment by kangarko** [comment]
Hey, sorry for late answer, I am out of country.

The error is caused due to a non-existing world that was set as your chest room location. That is why I recommended you to delete data.db file completely.

Have you done so? I am pretty confident it should fix the problem. If not, you can also rename settings.yml to settings_bac.yml and let Confiscate make a new settings file to test out that the problem is or is not coming from there.
