### ISSUE TITLE
Check Attributes: Maximalisation of certain enchantments

### ISSUE THREAD

**Issue by x1p** [kangarko/Confiscate#39]
Players make speed boots which is annoying.
I would like to control how high the maximum can be.
I'v seen speed boots anything from +0.3 to +2 when on feet. Thats really super fast!

**Comment by x1p** [comment]
Example 1:
Iron boots (0309)
Frostwalker II
When in main hand: +0.3 Speed
When in off hand: +0.3 Speed
When on feet: +0.3 Speed
When on leggs: +0.3 Speed
When on body: +0.3 Speed
When on head: +0.3 Speed
Unbreakable
Minecraft:iron_boots
NBT: 5 tag(s)

Example 2:
Diamond Boots (0313)
When on feet: +2 Speed
Minecraft:diamond_boots
NBT: 1 tag(s)

**Comment by kangarko** [comment]
Thank you for that suggestion. Checking nbt tags is a bigger work so I have to delay it for later or split it in chunks.

**Comment by kangarko** [comment]
You can control individual enchant's level manually in settings:

![a](https://i.imgur.com/Es6nghO.png)

**Comment by x1p** [comment]
I thought of that too, but speed or swiftness is not an enchantment according to the list https://hub.spigotmc.org/javadocs/spigot/org/bukkit/enchantments/Enchantment.html.
Or did I overlooked something? Can you tell me how this must be written? Something like: SPEED: 0.1?

**Comment by kangarko** [comment]
It's probably an Attribute (https://minecraft.gamepedia.com/Attribute). I can look into it at my next large chunk of time for feature updates.

**Comment by kangarko** [comment]
I am delaying this due to works on ChatControl and that attributes are dynamic so for now I did not see any possible solution. They would change according to enchants etc. so it's almost impossible to determine the correct value, or it would take tremendous time to do.

![a](https://i.imgur.com/qbp7GaU.png)

What I could do is to set an upper limit for each attribute for a player, but again that is very risky since I don't know how high they can go since this is changeable in spigot.yml and cannot go higher that that anyways:

![a](https://i.imgur.com/5ihH1TE.png)
