### ISSUE TITLE
Few hacked items are not affected by the plugin

### ISSUE THREAD

**Issue by ArtNRG** [kangarko/Confiscate#48]
Screenshots:
https://cdn.pbrd.co/images/HpBzpqj.png
https://cdn.pbrd.co/images/HpBzI09.png
Config: https://pastebin.com/raw/Ng2A1iqz
Confiscate version 1.8.2
Paper-1436 (MC: 1.12.2)

**Comment by kangarko** [comment]
Hello,

the first picture shows a pretty legitible boots item. All enchants can be naturally applied to it, and since Confiscate support custom items, it will also assume that the custom lore is correct.

I will patch the potions issue, but what's the hacked client you use and how to obtain it?

Sincerely,
kangarko

**Comment by ArtNRG** [comment]
I found these items in player's inventory. I don't know which client the player used.

Can you add a whitelist for lore?

**Comment by kangarko** [comment]
I have included a new setting that will confiscate all potions above a certain level. 

Added whitelist.
